[package]
org = "user"
name = "backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[module]]
name = "opensky_client"
path = "modules/opensky_client"

[[module]]
name = "compute_flight_distance"
path = "modules/compute_flight_distance"

[[module]]
name = "data_types"
path = "modules/data_types"
